Replace deprecated displayPrice methods
PrestaShop/statscatalog pull request #20
Opened 2021-10-19 15:00 UTC by Hlavtox

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | -
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#26293
| How to test?  | Create order and see no changes.

Related to https://github.com/PrestaShop/PrestaShop/pull/26288
Ping @PierreRambaud

2021-10-21 10:32 UTC, atomiix submitted a review, later dismissed

2021-10-22 07:28 UTC, PierreRambaud requested changes
You have to update prestashop compatibility :)

2021-10-22 15:47 UTC, PierreRambaud approved these changes

2021-10-22 15:49 UTC, merged

2021-10-22 15:49 UTC, PierreRambaud commented
Thank you @Hlavtox