Do not use hook AdminStatsModules alias, use displayAdminStatsModules & Bump version to 2.0.3
PrestaShop/statscatalog pull request #22
Opened 2021-12-29 10:53 UTC by PrestaEdit

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Do not use hook AdminStatsModules alias, use displayAdminStatsModules
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | n/d
| Possible impacts? | n/d

2021-12-29 14:06 UTC, PierreRambaud requested changes
The next version is 2.0.2

2021-12-30 15:29 UTC, PierreRambaud approved these changes, later dismissed

2022-01-03 16:34 UTC, atomiix commented on upgrade/index.php
> +header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
```suggestion
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
```

2022-01-04 08:20 UTC, PierreRambaud approved these changes

2022-01-04 08:20 UTC, merged

2022-01-04 08:20 UTC, PierreRambaud commented
Thank you @PrestaEdit